# Monte-Carlo Ternary Fission Simulator

In [48]:
%pylab inline
import numpy as np
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [2]:
alphapars=np.zeros(10)
Lpars=np.zeros(10)
Hpars=np.zeros(10)
mandZandA=np.zeros(10)
paxisandpP=np.zeros(6)
DEpars=np.zeros(17)
hatpars=np.zeros(14)
energies=np.zeros(3)
dD=np.zeros(7)

In [51]:
def getLightMass(avemL, sigmL, A):
    '''
    The mass of the light fragment is sampled 
    from a Gaussian distribution with an 
    average input value of avemL sigma of sigL. 
    AvemL, sigmL are obtained from reference x TBD.
    '''
    #Eventual code goes here
    mL= np.random.normal(avemL, sigmL, 1)
    #print np.mean(mL)
    #print np.std(mL, ddof=1)
    
    '''
    count, bins, ignored = plt.hist(mL, 50, normed=True)
    plt.plot(bins, 1/(sigmL * np.sqrt(2 * np.pi)) *
         np.exp( - (bins - avemL)**2 / (2 * sigmL**2) ),
         linewidth=2, color='r')
    plt.show()
    '''
    mandZandA[0]=mL
    
    return mandZandA

In [56]:
getLightMass(95, 15, 232)

array([  113.21055889,  1118.74291111,     4.        ,    37.        ,
          53.        ,     2.        ,    95.        ,   137.        ,
           4.        ,     0.        ])

In [4]:
def getfragmentZandA(mL, actA):
    '''
     Let the charge of the light and heavy 
     fragment be expressed as variable name 
     ZL and ZH. Using the mass from step 1, 
     the AL is computed by converting MeV to 
     amu. Since the alpha particle has Zalpha 
     of 2, use the value of AL to compute ZL, 
     ZH, and AH assuming an equal mass charge 
     distribution, that is, the ratio of ZL/AL 
     is equal to ZH/AH.
    '''
     #Eventual code goes here
    ZL=37 #e C
    ZH=90-ZL #e C
    Zalpha=2 #e C
    AL=95 #amu
    AH=232-AL #amu
    Aalpha=4 #amu
    malpha=4 #amu
    
    mandZandA[2]=malpha
    mandZandA[3]=ZL
    mandZandA[4]=ZH
    mandZandA[5]=Zalpha
    mandZandA[6]=AL
    mandZandA[7]=AH
    mandZandA[8]=Aalpha
    return mandZandA

In [5]:
mandZandA=getfragmentZandA(1, 1)
print mandZandA

[   0.    0.    4.   37.   53.    2.   95.  137.    4.    0.]


In [6]:
def getmH(mandZandA):
    #Semi-empirical mass formula constant terms
    av = 15.5 #MeV
    as1 = 17.2 #MeV
    ac = 0.72 #MeV
    asym = 23.2 #MeV
    ap = 12 #MeV
    delta = 0.
    if mandZandA[7]%2==0 and mandZandA[4]%2==0:
        delta = ap/np.sqrt(mandZandA[7])
    if mandZandA[7]%2==0 and mandZandA[4]%2!=0:
        delta = -ap/np.sqrt(mandZandA[7])
    print("delta:", delta, "pairing term")

    B = av*mandZandA[7] - as1*mandZandA[7]**(2./3.) - (ac*mandZandA[4]*(mandZandA[4] - 1.0))/(mandZandA[7]**(1./3.)) - (asym*(mandZandA[7] - 2.0*mandZandA[4])**2)/(mandZandA[7]) + delta
    mandZandA[1]=B
    
    return mandZandA

In [58]:
getmH(mandZandA)

('delta:', 0.0, 'pairing term')


array([  113.21055889,  1118.74291111,     4.        ,    37.        ,
          53.        ,     2.        ,    95.        ,   137.        ,
           4.        ,     0.        ])

In [8]:
def getE_alpha_scissandE_L_scissandE_H_sciss(EKB_act_infinity, EKB_act_sciss, EKT_act_infinity, deltaE_act, EKT_act_sciss, E_alpha_infinity):
    '''
    To compute the energy available for the three 
    particles coming out of the ternary fission, 
    we use the published numbers for the TKE of 
    binary fission minus the typical energy of the 
    LRA to figure out how much each fragment can have. 
    The variables and their initial values for U236 are: 
    EKB_act_infty = 168 +/- 4.5 MeV,
    EKB_act_sciss = 18.1 MeV, 
    EKT_act_infty = 155.5 +/- 0.8 MeV. 
    At scission, the alpha-accompanied fission
    has the initial values of: DeltaE_act = 4-5 MeV, 
    and EKT_act_sciss = 13 MeV. Furthermore, average
    kinetic energy of alpha particle at infinity 
    measured to be: E_alpha_infty = 16 MeV.
    
    These values have been obtained from Negele et al. 1978,
    and Asghar et al. 1970
    
    '''
    #Eventual code goes here
    E_alpha_sciss=128 #MeV
    E_L_sciss=256 #MeV
    E_H_sciss=512 #MeV
    
    energies[0]=E_alpha_sciss
    energies[1]=E_L_sciss
    energies[2]=E_H_sciss
    return energies

In [68]:
def getd0andD0(mandZandA):
    '''
    Using initial value of ZL and ZH, calculate 
    distance d0 of the electrostatic saddle point 
    by using equation 21, relating it to separation 
    distance D0.
    '''
    #Eventual code goes here
    D0=21.9 #fm
    d0=D0/((mandZandA[4]/mandZandA[3])+1)
    
    dD[2]=d0
    dD[3]=D0
    return dD

In [69]:
getd0andD0(mandZandA)

array([ 10.        ,  22.        ,   9.00333333,  21.9       ,
         9.30313355,  22.73638936,   2.3       ])

In [10]:
def getAvedandAveD(EKT_act_infinity, EKT_act_sciss, E_alpha_infinity,E_alpha_sciss,mandZandA):
    '''
    Use a guessed value for mean alpha KE 
    and equation 20 in order to calculate 
    average of d and D
    '''
    #Eventual code goes here
    aved=10 #fm
    aveD=22 #fm
    
    dD[0]=aved
    dD[1]=aveD
    return dD

In [63]:
def getdandD(sigma_xp, dD, sigma_D):
    '''
    To account for uncertainty in separation 
    distance D, choose random values of D 
    from a Gaussian, equation 23 (with a width 
    of sigma_D = 1 fm). The uncertainty will 
    thus be given by summing a random variable
    (defined by equation 24b) with the value 
    of the separation distance obtained from 
    equation 20.  Likewise, as for the distance 
    d of the electrostatic saddle point, its 
    uncertainty is given by sampling d from a
    Gaussian distribution (equation 25), and 
    then by summing a random variable 
    (equation 26b) to d value from equation 20. 
    Where sigma_xp=0.93.
    '''
    
    d=np.random.normal(dD[2], 1) #fm
    D=np.random.normal(dD[3], sigma_D, 1) #fm
    
    dD[4]=d
    dD[5]=D
    return dD

In [70]:
dD=getdandD(1, dD, 1)
print dD

[ 10.          22.           9.00333333  21.9          9.01011023
  23.12361082   2.3       ]


In [71]:
def getxpandypandzpandRc(dD, xpin, ypin, zpin,sigma_xp, sigma_yp, sigma_zp):
    '''
    To compute the uncertainty of the alpha 
    particle position along the primed axis, 
    use Gaussian distribution around d0, given 
    by equation 25, where x’ = d-d0. One can 
    also use the same approach for figuring out 
    the uncertainty along y’ and z’, while 
    assuming that sigma_y’ = sigma_z’. Using 
    equation 28, one can then compute Rc from 
    equation 27.
    '''
    #Eventual code goes here
    xpout=1.2 #fm
    ypout=2.3 #fm
    zpout=2.2 #fm
    Rc=ypout #fm
    
    paxisandpP[0]=xpout
    paxisandpP[1]=ypout
    paxisandpP[2]=zpout
    dD[6]=Rc
    return paxisandpP, dD

In [14]:
def getPxpandPypandPzp(Pxpin, Pypin, Pzpin, sigma_xp, sigma_yp, sigma_zp):
    '''
    Use the uncertainty principle to select 
    the initial momentum of the alpha particle 
    using a Gaussian distribution, employing 
    equations 30 and 31, where 
    sigma_x’ = 0.93 fm 
    and sigma_y’ = sigma_z’ = 1.3 fm.
    
    The choice
of sigma_x' is obtained from the assumption that an estimate
of sigma_x', may be of an order of magnitude of the
root mean square of the radius of the alpha particle.
The values of sigma_y' =sigma_z', are chosen to be sqrt(2) sigma_x' rather
arbitrarily (larger and smaller values of  were
used, and they seemed to give poorer agreement between
theory and experiment).
    '''
    #Eventual code goes here
    Pxpout=2.4 #kg*m/s
    Pypout=4.6 #kg*m/s
    Pzpout=4.4 #kg*m/s
    
    paxisandpP[3]=Pxpout
    paxisandpP[4]=Pypout
    paxisandpP[5]=Pzpout
    return paxisandpP

In [15]:
def getVL0andVH0(mandZandA):
    '''
    From conservation of momentum, explain what is 
    used to calculate them
    
    two default values given the numbers in the 
    paper come out to be
    VL0 = 0.013c
    and VH0 = 0.009c.
    '''
   
    M=236
    VH0 = 2*mandZandA[0]*M/(mandZandA[1]*(mandZandA[1] + 2*mandZandA[2])) #c m/s
    VL0 = (M-mandZandA[1]*VH0**2)/mandZandA[0] #c m/s
    
    DEpars[15]=VL0
    DEpars[16]=VH0
    return DEpars, VH0, VL0

In [16]:
def getR0andV0andT0(mandZandA):
    '''
    Depending on your fission fragments, 
    select the radius of each one from reference 
    x TBD and compute the average radii using 
    equation 11. Compute the average speed using 
    equation 12 and find T0 using equation 13.
    '''
    #Eventual code goes here
    R0=4.86 #fm
    V0=(DEpars[15]+DEpars[16])/2 #c m/s
    T0=V0/R0 #1/c m/s
    
    DEpars[12]=R0
    DEpars[13]=V0
    DEpars[14]=T0
    
    return DEpars

In [85]:
print DEpars

[  2.05365646e+01   1.83780038e+00  -4.73251029e-01  -4.11522634e+00
   2.24811616e+01   4.74140751e+00   2.16840434e-19   1.47137516e-02
   3.32049108e+01   3.28893604e+00   5.38673220e-01   4.70081288e+00
   4.86000000e+00   4.20083533e+00   8.64369409e-01   8.39114499e+00
   1.05256639e-02]


In [18]:
def getpositionandvelocity(mandZandA, dD):
    '''
     Using equations in Table 1, compute initial coordinates 
     and velocities of light, heavy and alpha 
     particles in the center of mass frame. The 
     velocity of alpha fragment is to be chosen 
     at random following a Gaussian distribution - with what parameter values? 
     In addition, velocities of the heavy and light 
     fragments are to be modified as to keep the 
     total momentum of the system as zero in the 
     cm frame. In other words, the values which the 
     L and H fragment can attain will be constricted 
     to whatever keeps total CM momentum zero
    '''
    #Eventual code goes here
    Vxalpha=0.6 #fm/s
    Vyalpha=-0.2 #fm/s
    Vzalpha=2.4 #fm/s
    
    mLH=mandZandA[0]+mandZandA[1]
    M=mandZandA[0]+mandZandA[1]+mandZandA[2]
    deltax=dD[4]-(mandZandA[1]/mLH)*dD[5]
    deltaV=(mandZandA[0]*DEpars[15]-mandZandA[1]*DEpars[16]+mandZandA[2]*Vxalpha)/mLH
    
    xL=(mandZandA[2]/M)*deltax+(mandZandA[1]/M)*dD[5] #fm
    xH= -(mLH/M)*deltax-dD[5]+dD[4] #fm
    xalpha= -(mLH/M)*deltax #fm
    
    yL= -(mandZandA[2]/M)*dD[6] #fm
    yH=yL #fm
    yalpha=(mLH/M)*dD[6] #fm
    
    zL=0. #fm
    zH=0. #fm
    zalpha=20. #fm  this is supposed to be 0 
    
    VxL=0.5 #fm/s
    VxH=-0.3 #fm/s
    
    VyL=-(mandZandA[2]/mLH)*Vyalpha #fm/s
    VyH=VyL #fm/s
    
    VzL=-(mandZandA[2]/mLH)*Vzalpha #fm/s
    VzH=VzL #fm/s
    
    
    alphapars[0]=xalpha
    alphapars[1]=yalpha
    alphapars[2]=zalpha
    alphapars[3]=Vxalpha
    alphapars[4]=Vyalpha
    alphapars[5]=Vzalpha
    
    Lpars[0]=xL
    Lpars[1]=yL
    Lpars[2]=zL
    Lpars[3]=VxL
    Lpars[4]=VyL
    Lpars[5]=VzL
    
    Hpars[0]=xH
    Hpars[1]=yH
    Hpars[2]=zH
    Hpars[3]=VxH
    Hpars[4]=VyH
    Hpars[5]=VzH
    return alphapars, Lpars, Hpars

In [82]:
def getDEparameters(mandZandA, DEpars,  Lpars, alphapars, t):
    '''
    Using results from equations 11-13, and 
    the initial positions/velocities found in 
    previous step, compute differential
    equation parameters found in equations 7-10.
    '''
    c=299792458 #m/s
    
  
    xhL=Lpars[0]/DEpars[12] #no unit
    xhalpha=alphapars[0]/DEpars[12] #no unit
    vhxL=Lpars[3]/DEpars[13] #no unit
    vhxalpha=alphapars[3]/DEpars[13] #no unit
    
    yhL=Lpars[1]/DEpars[12] #no unit
    yhalpha=alphapars[1]/DEpars[12] #no unit
    vhyL=Lpars[4]/DEpars[13] #no unit
    vhyalpha=alphapars[4]/DEpars[13] #no unit
    
    zhL=Lpars[2]/DEpars[12] #no unit
    zhalpha=alphapars[2]/DEpars[12] #no unit
    vhzL=Lpars[5]/DEpars[13] #no unit
    vhzalpha=alphapars[5]/DEpars[13] #no unit
    
    
    Ax=xhL-xhalpha #no unit
    Bx=(1+mandZandA[0]/mandZandA[1])*xhL+(mandZandA[2]/mandZandA[1])*xhalpha #no unit
    Cx=(mandZandA[0]/mandZandA[1])*xhL+(1+mandZandA[2]/mandZandA[0])*xhalpha #no unit
    
    Ay=yhL-yhalpha #no unit
    By=(1+mandZandA[0]/mandZandA[1])*yhL+(mandZandA[2]/mandZandA[1])*yhalpha #no unit
    Cy=(mandZandA[0]/mandZandA[1])*yhL+(1+mandZandA[2]/mandZandA[0])*yhalpha #no unit
    
    Az=zhL-zhalpha #no unit
    Bz=(1+mandZandA[0]/mandZandA[1])*zhL+(mandZandA[2]/mandZandA[1])*zhalpha #no unit
    Cz=(mandZandA[0]/mandZandA[1])*zhL+(1+mandZandA[2]/mandZandA[0])*zhalpha #no unit
    
    
    A=(Ax**2+Ay**2+Az**2)**(3/2) #no unit
    B=(Bx**2+By**2+Bz**2)**(3/2) #no unit
    C=(Cx**2+Cy**2+Cz**2)**(3/2) #no unit
    
    
    th=t/DEpars[14] #no unit
    beta0=DEpars[13]/c #no unit
    
    
    DEpars[0]=A
    DEpars[1]=Ax
    DEpars[2]=Ay
    DEpars[3]=Az
    DEpars[4]=B
    DEpars[5]=Bx
    DEpars[6]=By
    DEpars[7]=Bz
    DEpars[8]=C
    DEpars[9]=Cx
    DEpars[10]=Cy
    DEpars[11]=Cz
    
    hatpars[0]=xhL
    hatpars[1]=yhL
    hatpars[2]=zhL
    hatpars[3]=vhxL
    hatpars[4]=vhyL
    hatpars[5]=vhzL
    hatpars[6]=xhalpha
    hatpars[7]=yhalpha
    hatpars[8]=zhalpha
    hatpars[9]=vhxalpha
    hatpars[10]=vhyalpha
    hatpars[11]=vhzalpha
    hatpars[12]=th
    hatpars[13]=beta0
    
    return DEpars, hatpars

In [20]:
 def getPalpha(alphapars):
        pxalpha=1
        pyalpha=2
        pzalpha=7
        
        alphapars[6]=pxalpha
        alphapars[7]=pyalpha
        alphapars[8]=pzalpha
        alphapars[9]=alphapars[6]+alphapars[7]+alphapars[8]
        return alphapars

In [21]:
def getdistanceL(alphapars, Lpars):
    from math import pow
    distanceL=pow((pow(alphapars[0]-Lpars[0], 2)+pow(alphapars[1]-Lpars[1], 2)+pow(alphapars[2]-Lpars[2], 2)), 0.5)
    return distanceL

In [22]:
def getdistanceH(alphapars, Hpars):
    from math import pow
    distanceH=pow((pow(alphapars[0]-Hpars[0], 2)+pow(alphapars[1]-Hpars[1], 2)+pow(alphapars[2]-Hpars[2], 2)), 0.5)
    return distanceH

In [83]:
def initparameters():
    avemL=27.
    sigmL=3.
    M=232
    actA=239.
    EKB_act_infinity=124
    EKB_act_sciss=114
    EKT_act_infinity=154
    deltaE_act=186
    EKT_act_sciss=287
    EKT_act_sciss=268
    E_alpha_infinity=298
    Zalpha=2
    sigma_xp=1.3
    sigma_D=1
    xpin=25
    ypin=12
    zpin=14
    sigma_yp=0.93
    sigma_zp=0.93
    Pxpin=13
    Pypin=23
    Pzpin=33
    inputs=50
    mH=137
    malpha=4
    zalpha=2
    A=236
    t=4
    
    mandZandA=getLightMass(avemL,sigmL, A)
    mandZandA=getfragmentZandA(mandZandA,actA)
    energies=getE_alpha_scissandE_L_scissandE_H_sciss(EKB_act_infinity,EKB_act_sciss,EKT_act_infinity,deltaE_act,EKT_act_sciss,E_alpha_infinity)
    dD=getd0andD0(mandZandA)
    dD=getAvedandAveD(EKT_act_infinity,EKT_act_sciss,E_alpha_infinity,energies,mandZandA)
    #dD=getdandD(dD,sigma_xp,sigma_D)
    paxisandpP,dD=getxpandypandzpandRc(dD,xpin,sigma_xp,ypin,sigma_yp,zpin, sigma_zp)
    paxisandpP=getPxpandPypandPzp(Pxpin,Pypin,Pzpin,sigma_xp,sigma_yp,sigma_zp)
    DEpars=getVL0andVH0(mandZandA)
    DEpars=getR0andV0andT0(mandZandA)
    
    alphapars, Lpars, Hpars=getpositionandvelocity(mandZandA,dD)
    alphapars=getPalpha(alphapars)
    
    DEpars, hatpars=getDEparameters(mandZandA, DEpars, Lpars, alphapars, t)

    
    return mandZandA, energies,dD, paxisandpP, alphapars, Lpars, Hpars, DEpars, hatpars

In [84]:
initparameters()

(array([   28.11011551,  1118.74291111,     4.        ,    37.        ,
           53.        ,     2.        ,    95.        ,   137.        ,
            4.        ,     0.        ]),
 array([ 128.,  256.,  512.]),
 array([ 10.        ,  22.        ,   9.00333333,  21.9       ,
          9.01011023,  23.12361082,   2.3       ]),
 array([ 1.2,  2.3,  2.2,  2.4,  4.6,  4.4]),
 array([ 13.49964169,   2.29200593,  20.        ,   0.6       ,
         -0.2       ,   2.4       ,   1.        ,   2.        ,
          7.        ,  10.        ]),
 array([  2.24313515e+01,  -7.99407030e-03,   0.00000000e+00,
          5.00000000e-01,   6.97561049e-04,  -8.37073258e-03,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00]),
 array([-0.6138589 , -0.00799407,  0.        , -0.3       ,  0.00069756,
        -0.00837073,  0.        ,  0.        ,  0.        ,  0.        ]),
 array([  2.05365646e+01,   1.83780038e+00,  -4.73251029e-01,
         -4.11522634e+00,   2.2

In [25]:
def writeresults(filename, results, label):
    '''
    Once numerical solution for each equation 
    of motion has been completed, write file 
    to filename with particle trajectory data.
    '''
    
    matrix=np.array([alphapars, Lpars, Hpars, mandZandA])
    writer=file('test.txt', 'a')
    np.savetxt(writer, (mandZandA, alphapars, Lpars, Hpars), fmt='%.3f', header=label)
    writer.close()
    #!cat test.txt
    return matrix
    #Does this return anything?

In [26]:
def solveequationsofmotion(DEpars,hatpars,mandZandA, momentum, distanceL, distanceH):
    '''
    All of the preceding parameters are to 
    be passed in order to set up differential 
    equations of motion for the light and alpha 
    particles, equations 5 and 6.
    The coupled first-order differential 
    equations are to be solved numerically by 
    employing the Adams-Moulton predictor-corrector 
    method. This will compute the solutions to the 
    equations of motion (while the equation of motion 
    for the heavy fragment can be obtained via 
    conservation of momentum).
    '''
    mome=momentum-1
    distanceL=distanceL-1
    distanceH=distanceH-1
    print mome
    print distanceL
    print distanceH
            
    #Eventual code goes here
    #Return results  -- WHAT FORM ARE THE RESULTS IN?
    
    return mome, distanceL, distanceH
    #return xalpha, yalpha, zalpha, pxalpha, pyalpha, pzalpha, xL, yL, zL, xH, yH, zH

In [28]:
Palpha=2
PL=2
PH=2
SP=Palpha+PL+PH
print SP
while True:
    Palpha=float(raw_input())
    PL=float(raw_input())
    PH=float(raw_input())
    SP=Palpha+PL+PH
    print SP
    if SP==0:
        break
    

6
0
1
-1
0.0


In [29]:
def m(A, E):
    
    e=0
    events=np.array([e,E])
    while events[0]<E:
        events[0]=events[0]+1
        mandZandA, energies,dD, paxisandpP, alphapars, Lpars, Hpars, DEpars, hatpars=initparameters()
        
        distanceL=getdistanceL(alphapars, Lpars)
        distanceH=getdistanceH(alphapars, Hpars)
        momentum=alphapars[9]
        
        filename="test.txt"
        writer=file('test.txt', 'a')
        np.savetxt(writer, events, fmt='%d',header='event', newline=' ')
        writer.close()
        writeresults(filename, 1, "test datas")
        
        while True:
            #numerical solver
            
                momentum, distanceL, distanceH=solveequationsofmotion(DEpars,hatpars,mandZandA, momentum, distanceL, distanceH)
    
                if momentum==0 or distanceL<=0.8 or distanceH<=0.8:
                #write results
                        print "Results"
                        alphapars[9]=momentum
                    
                        writeresults(filename, 1, "test datae")
                    
                        break
                    

In [30]:
m(0, 4)

9.0
21.0261241574
22.4369366599
8.0
20.0261241574
21.4369366599
7.0
19.0261241574
20.4369366599
6.0
18.0261241574
19.4369366599
5.0
17.0261241574
18.4369366599
4.0
16.0261241574
17.4369366599
3.0
15.0261241574
16.4369366599
2.0
14.0261241574
15.4369366599
1.0
13.0261241574
14.4369366599
0.0
12.0261241574
13.4369366599
Results
9.0
21.0261241574
22.4369366599
8.0
20.0261241574
21.4369366599
7.0
19.0261241574
20.4369366599
6.0
18.0261241574
19.4369366599
5.0
17.0261241574
18.4369366599
4.0
16.0261241574
17.4369366599
3.0
15.0261241574
16.4369366599
2.0
14.0261241574
15.4369366599
1.0
13.0261241574
14.4369366599
0.0
12.0261241574
13.4369366599
Results
9.0
21.0261241574
22.4369366599
8.0
20.0261241574
21.4369366599
7.0
19.0261241574
20.4369366599
6.0
18.0261241574
19.4369366599
5.0
17.0261241574
18.4369366599
4.0
16.0261241574
17.4369366599
3.0
15.0261241574
16.4369366599
2.0
14.0261241574
15.4369366599
1.0
13.0261241574
14.4369366599
0.0
12.0261241574
13.4369366599
Results
9.0
21.026124157